### ISSUE TITLE
Repeated Bytes isn't recursive as described.

### ISSUE THREAD

**Issue by zander** [bitjson/bch-loops#2]
The spec states that begin/until are using a stack. And this makes them recursive. You can have a loop in a loop.

This doesn't vibe with the `Repeated Bytes` concept as described as that is stated to be a VM-global variable.

I would drop the idea of adding a global state to the VM and simply make the UNTIL opcode do the math of the amount of bytes moved (until-pos minus begin-pos).

While this is unfair in case of skipped blocks, its pretty darn cheap to do.

**Comment by bitjson** [comment]
Hey @zander, thanks for the detailed review! Did you mean to close this issue? 

I'm not sure if I fully understand what you mean, but I'm very glad you're checking my assumptions on how we could limit abuse. I really need to do an example implementation to validate everything, but I haven't had time yet.

I definitely expect that loops can be contained inside other loops (and OP_IF branches can be inside/outside each) – is there some issue with simply counting up the cumulative number of bytes "replayed" that I'm missing?
