### ISSUE TITLE
Motivation reads a bit glib :-)

### ISSUE THREAD

**Issue by tomFlowee** [bitjson/bch-loops#3]
(yes, I have a new account as github blocked my old one).

At this point the 'Motivation' chapter has this text;

> Loops were originally excluded from this design on the mistaken
> assumption that they risk consuming excessive validation 
> resources. In reality, a small number of VM operations make up 
> the majority of resource usage during transaction validation, 
> and any implementation of bounded loops can be many orders 
> of magnitude faster than the most pathological VM bytecode
> constructions.

This makes people believe that the _actual_ loops are the thing that was the worry. Naturally that makes no sense, jumping a number of times is indeed cheap, and that was never the problem.
The reason loops were disabled was the fact that it makes calling those really heavy resource-usage type of operations much much cheaper.

The logic simply is that if you have an operation that has cost Y to it, and then you surround it with a bunch of opcodes to be able to repeatedly do that same operation, you worry about the `n * Y` cost. Not the overhead of looping, but the fact that it became cheap to multiply cost Y.

It probably makes sense to be honest about this in the motivation and look at what kind  of mitigation the original Satoshi stack had and compare that with what you present.

**Comment by bitjson** [comment]
Cleaned up, thanks!
